from database import SessionLocal, engine
from models import Base, Question

# Crea le tabelle se non esistono
Base.metadata.create_all(bind=engine)

db = SessionLocal()

# Inserimento record iniziali
db.add_all([
    Question(question="How many target systems are in scope, and what are their names?", system_type="Generic"),
    Question(question="For each target system, what is its priority and business/operational criticality level?", system_type="Generic"),
    Question(question="Is the target system deployed as SaaS, on‑premises, or hybrid?", system_type="Generic"),
    Question(question="Are there any ongoing migrations, upgrades, or critical activities on this target system that could impact the IGA integration?", system_type="Generic"),
    Question(question="What is the main technology stack of the target system (platform, vendor, version)?", system_type="Generic"),
    Question(question="What type of identity repository does the target system use (e.g., relational DB, LDAP directory, other)?", system_type="Generic"),
    Question(question="Is administrative or integration access to the target system restricted to specific technical accounts or network segments?", system_type="Generic"),
    Question(question="Does the target system use internal authentication, external authentication (e.g., AD/LDAP/IdP/SSO), or a combination of both?", system_type="Generic"),
    Question(question="Is there a defined naming convention for user accounts on the target system, and how is it structured?", system_type="Generic"),
    Question(question="Which user types are managed in the target system (e.g., employees, contractors, external partners, service accounts)?", system_type="Generic"),
    Question(question="Which user lifecycle states are managed in the target system (e.g., active, suspended, disabled, terminated)?", system_type="Generic"),
    Question(question="Which key user attributes are stored and managed in the target system that are relevant for IGA?", system_type="Generic"),
    Question(question="Can a person have multiple accounts on the same target system (e.g., standard and privileged), or is there a single account per identity?", system_type="Generic"),
    Question(question="What is the approximate number of user accounts currently registered in the target system?", system_type="Generic"),
    Question(question="What types of permissions or access rights are managed (e.g., groups, roles, profiles), and approximately how many distinct items exist?", system_type="Generic"),
    Question(question="Is there a base role or default profile used to drive rule‑based account or entitlement assignment?", system_type="Generic"),
    Question(question="Is there a role hierarchy or role model that allows evaluation of intersections, inclusions, or inheritance between roles?", system_type="Generic"),
    Question(question="How are exceptions handled when multiple roles are assigned to the same user and conflicts or overlaps may occur?", system_type="Generic"),
    Question(question="Are there standard accounts or default permissions that must always be assigned to specific classes of users (e.g., by organization, job family, contract type)?", system_type="Generic"),
    Question(question="Are access requests for this target system currently managed through an IT shop, service catalog, or request portal, and how?", system_type="Generic"),
    Question(question="In which environments (DEV, TEST, PROD) is the target system available, and which environments are in scope for IGA integration?", system_type="Generic"),
    Question(question="Which operations must the IGA solution manage for this target system (e.g., create, update, disable, delete accounts; add/remove roles; password reset; unlock)?", system_type="Generic"),
    Question(question="Which integration modes and interfaces are available or preferred for this target system (e.g., standard connector, direct DB access, REST APIs, SCIM, file‑based)?", system_type="Generic"),
    Question(question="Are there any particular or critical situations we should be aware of (e.g., legacy constraints, manual workarounds, regulatory or SoD constraints)?", system_type="Generic"),
    Question(question="What is the expected migration and go‑live scenario for this target system (e.g., big‑bang vs. phased, coexistence with legacy processes, blackout periods)?", system_type="Generic"),
    Question(question="How many Active Directory domains are in scope, and what are their names?", system_type="AD-Azure"),
    Question(question="Which environments are available for Active Directory (e.g., PROD only, or also DEV/TEST/UAT)?", system_type="AD-Azure"),
    Question(question="Where is Active Directory located in the network, and which firewall rules or network constraints are relevant for the IGA integration?", system_type="AD-Azure"),
    Question(question="What is the current process for account creation, modification, and disabling in Active Directory?", system_type="AD-Azure"),
    Question(question="What is the current structure and naming convention used for SAMAccountName and UPN?", system_type="AD-Azure"),
    Question(question="Can we perform a deep dive on a sample employee account to review all relevant attributes and their values?", system_type="AD-Azure"),
    Question(question="Can we perform a deep dive on a sample external account to review all relevant attributes and their values?", system_type="AD-Azure"),
    Question(question="What is the current OU hierarchy structure in Active Directory, and how is it organized (e.g., by country, organization, function)?", system_type="AD-Azure"),
    Question(question="Are there dedicated OUs for employees and separate OUs for external users?", system_type="AD-Azure"),
    Question(question="Are there dedicated OUs for different countries or geographic regions?", system_type="AD-Azure"),
    Question(question="Is there a dedicated OU (or set of OUs) for groups, and how is it structured?", system_type="AD-Azure"),
    Question(question="Are Office 365 licenses assigned via group membership in Active Directory or Azure AD?", system_type="AD-Azure"),
    Question(question="What is the approximate number of groups defined, and are meaningful descriptions available for these groups?", system_type="AD-Azure"),
    Question(question="How many managed applications are in scope, and is there an attribute available to identify the application associated with each group or entitlement?", system_type="AD-Azure"),
    Question(question="Are there standard groups that must be automatically assigned to specific user classes (e.g., by organization, country, role)?", system_type="AD-Azure"),
    Question(question="What is the current Azure AD Connect synchronization schedule (frequency, timing)?", system_type="AD-Azure"),
    Question(question="Which attributes are included in the synchronization scope between Active Directory and Azure AD?", system_type="AD-Azure"),
    Question(question="Are there any customizations or particular/critical scenarios in Active Directory or Azure AD that we should be aware of for the IGA integration?", system_type="AD-Azure"),
    Question(question="What is the approximate number of users to be managed per country?", system_type="AD-Azure"),
    Question(question="What is the current structure and naming convention used for SAMAccountName and UPN?", system_type="AD-Azure"),
    Question(question="How is the OU hierarchy currently structured in Active Directory (e.g., by country, organization, function)?", system_type="AD-Azure"),
    Question(question="Which rules are currently applied to determine in which OU a new account must be created?", system_type="AD-Azure"),
    Question(question="Which rules govern the provisioning of individual attributes (both basic and any other mandatory attributes) for user accounts?", system_type="AD-Azure"),
    Question(question="Is there a dedicated OU (or set of OUs) for disabled accounts, and how is it used?", system_type="AD-Azure"),
    Question(question="Under which conditions are user accounts moved between OUs, and how is this process managed?", system_type="AD-Azure"),
    Question(question="How are user accounts managed with respect to the value of the “company” attribute (e.g., OU placement, group membership, licenses)?", system_type="AD-Azure"),
    Question(question="Which groups must be assigned by default based on specific rules (e.g., country, organization, role, contract type)?", system_type="AD-Azure"),
    Question(question="How are Office 365 licenses currently assigned and managed (e.g., via group membership, direct assignment, other rules)?", system_type="AD-Azure"),
    Question(question="Are there any exceptions or non‑standard scenarios that should be considered to avoid issues or surprises during the IGA integration?", system_type="AD-Azure"),
    Question(question="Is the target system deployed on‑premises?", system_type="Target DB"),
    Question(question="Where is the target system located in the network (e.g., LAN, Secure Zone, DMZ)?", system_type="Target DB"),
    Question(question="Does the target system use a local database as its primary authentication mechanism?", system_type="Target DB"),
    Question(question="Does the target system use a database (e.g., SQL) as its authorization system?", system_type="Target DB"),
    Question(question="Is the target system available only in the PROD environment, or are there additional environments (e.g., DEV, TEST, UAT)?", system_type="Target DB"),
    Question(question="Which database technology is used by the target system (e.g., Oracle, Microsoft SQL Server, other)?", system_type="Target DB"),
    Question(question="Is there a separate instance of the target system for each country or business unit?", system_type="Target DB"),
    Question(question="Are there currently any relevant activities or projects ongoing that could impact the IGA integration for this target system?", system_type="Target DB"),
    Question(question="Is it necessary to create user records in the local database in order to grant access to the application?", system_type="Target DB"),
    Question(question="What is the key/username that must be used to uniquely identify users in the local database?", system_type="Target DB"),
    Question(question="Is it possible to create more than one record in the local database for the same user (e.g., multiple profiles or accounts)?", system_type="Target DB"),
    Question(question="Which attributes must be specified in the user record in the local database, and for each attribute, is it mandatory or optional?", system_type="Target DB"),
    Question(question="Is there a specific attribute in the user record that represents the user status, and which status values are possible?", system_type="Target DB"),
    Question(question="Is there a basic security group in Active Directory that is required to allow access to the application?", system_type="Target DB"),
    Question(question="Is user profiling (e.g., roles, permissions) managed directly in the local database?", system_type="Target DB"),
    Question(question="Is there a separate table in the database dedicated to access rights/permissions?", system_type="Target DB"),
    Question(question="Which attributes are present in the access‑rights table in the database (e.g., code, description, type, scope)?", system_type="Target DB"),
    Question(question="Is there a specific naming convention (nomenclature) used for access rights in the database?", system_type="Target DB"),
    Question(question="Is there a user‑friendly description stored in the database for each access right?", system_type="Target DB"),
    Question(question="Is profiling in the database managed via specific attributes on the user table, or via a separate table that manages assignments between access rights and users?", system_type="Target DB"),
    Question(question="Are the same profiles/access‑rights structures used across the different instances of the target system?", system_type="Target DB"),
    Question(question="Is access to the application allowed to both employees and external users, or only to employees?", system_type="Target DB"),
    Question(question="Are there internal departments/areas that mostly or exclusively have access to the system, or that have access with specific privileged profiles?", system_type="Target DB"),
    Question(question="Are there internal departments/areas that must not have access to the system, or that must not receive certain access profiles?", system_type="Target DB"),
    Question(question="How does the current process work when a user needs to obtain access to the application for the first time?", system_type="Target DB"),
    Question(question="How does the current process work for changes to existing accounts (e.g., role changes, department changes, profile updates)?", system_type="Target DB"),
    Question(question="What happens to access rights and profiles when a user is disabled or terminated in the system?", system_type="Target DB"),
    Question(question="Are there any Segregation of Duties (SoD) rules or constraints defined among the access rights/profiles?", system_type="Target DB"),
    Question(question="Are there any customizations or particular/critical scenarios that we should consider for this target system?", system_type="Target DB"),
    Question(question="Will a dedicated service account be created for the database connector with read/write permissions, and what are the expected privileges for this account?", system_type="Target DB"),
    Question(question="Is the target system SAP  S4/HANA?", system_type="SAP"),
    Question(question="Where is the system located from an identity and network perspective (e.g., integrated with Azure AD, other network zones)?", system_type="SAP"),
    Question(question="Does the system use Azure AD (or Azure services) as its primary authentication mechanism?", system_type="SAP"),
    Question(question="Does the system rely on Azure (or other external services) as its authorization source, or is authorization managed locally in SAP?", system_type="SAP"),
    Question(question="Is there a single SAP instance, or are there multiple instances (e.g., per country, business unit, environment)?", system_type="SAP"),
    Question(question="Is it necessary to create user entries in the local SAP user database in order to grant access (in addition to Azure AD integration)?", system_type="SAP"),
    Question(question="What key/username should be used as the unique identifier for users in SAP , and which naming convention is expected?", system_type="SAP"),
    Question(question="Is it possible to create more than one user record in SAP for the same physical person (e.g., technical vs. personal account)?", system_type="SAP"),
    Question(question="Which attributes must be specified in the SAP user record, and for each attribute, is it mandatory or optional?", system_type="SAP"),
    Question(question="Is there a specific attribute that represents the user status in SAP , and which status values are possible?", system_type="SAP"),
    Question(question="Is there a basic security group or role that is always required to allow basic access to SAP ?", system_type="SAP"),
    Question(question="How is the profiling/authorization model structured (e.g., roles, profiles, transactions)?", system_type="SAP"),
    Question(question="Which objects can be directly assigned to users (only roles, or also profiles/other objects)?", system_type="SAP"),
    Question(question="What is the expected number of roles to be managed in SAP ?", system_type="SAP"),
    Question(question="Is there a specific naming convention defined for roles in SAP ?", system_type="SAP"),
    Question(question="Is there a user‑friendly description maintained for each role in SAP ?", system_type="SAP"),
    Question(question="Which environments exist for SAP (e.g., DEV, TEST, PROD), and how are they configured and aligned?", system_type="SAP"),
    Question(question="Is access to SAP allowed for both employees and external users, or only for employees?", system_type="SAP"),
    Question(question="Are there internal departments/areas that mostly or exclusively have access to SAP , or that typically use specific privileged profiles?", system_type="SAP"),
    Question(question="Are there internal departments/areas that must not have access to SAP , or that must not receive specific access profiles or roles?", system_type="SAP"),
    Question(question="What is the current process to request new access rights in SAP (e.g., via ServiceNow), and how is it managed end‑to‑end?", system_type="SAP"),
    Question(question="Are there any customizations or particular/critical scenarios in SAP that we should consider for the IGA integration?", system_type="SAP"),
    Question(question="Is a Segregation of Duties (SoD) framework already in place for SAP , and how is it implemented (tools, rules, processes)?", system_type="SAP"),
    Question(question="Will the technical connection be established via the SAP message server, and what are the relevant connection details?", system_type="SAP"),
    Question(question="How many LDAP directory instances are in scope, and what are their base DNs (Distinguished Names)?" , system_type="LDAP"),
    Question(question="Which environments are available for the LDAP directory (e.g., PROD only, or also DEV/TEST/UAT)?" , system_type="LDAP"),
    Question(question="Where is the LDAP directory located in the network, and which firewall rules or network constraints are relevant for the IGA integration (e.g., ports 389/LDAP, 636/LDAPS)?" , system_type="LDAP"),
    Question(question="Which LDAP protocol version is supported (LDAPv2, LDAPv3), and is TLS/SSL (LDAPS or StartTLS) enforced?" , system_type="LDAP"),
    Question(question="What type of LDAP directory software is deployed (e.g., OpenLDAP, Oracle Internet Directory, 389 DS, IBM Tivoli Directory), and what version?" , system_type="LDAP"),
    Question(question="Is there a replication topology in place (e.g., multi-master, provider-consumer), and which node should the IGA platform connect to for read/write operations?" , system_type="LDAP"),
    Question(question="Which bind DN (service account) will be used by the IGA platform, and what permissions does it have (read, write, create, delete)?" , system_type="LDAP"),
    Question(question="Are there connection limits, rate-limiting policies, or size/time limits configured on the LDAP server that may impact bulk operations?" , system_type="LDAP"),
    Question(question="Are referrals enabled, and should the IGA connector follow them?" , system_type="LDAP"),
    Question(question=" What is the current DIT (Directory Information Tree) structure, and how is it organized (e.g., by country, organization, function)?" , system_type="LDAP"),
    Question(question=" Are there dedicated subtrees (OUs or container entries) for employees and separate ones for external users?" , system_type="LDAP"),
    Question(question=" Are there dedicated subtrees for different countries or geographic regions?" , system_type="LDAP"),
    Question(question=" Is there a dedicated subtree for groups/roles, and how is it structured?" , system_type="LDAP"),
    Question(question=" Is there a dedicated subtree for disabled/deprovisioned accounts, and how is it used?" , system_type="LDAP"),
    Question(question=" Under which conditions are user entries moved between subtrees, and how is this process managed?" , system_type="LDAP"),
    Question(question=" Which rules are currently applied to determine in which subtree a new entry must be created?" , system_type="LDAP"),
    Question(question=" Which objectClasses are used for user entries (e.g., inetOrgPerson, posixAccount, custom objectClasses)?" , system_type="LDAP"),
    Question(question=" What is the current naming convention for the RDN (Relative Distinguished Name) of user entries (e.g., uid=, cn=)?" , system_type="LDAP"),
    Question(question=" Which attributes are mandatory and which are optional for user provisioning?" , system_type="LDAP"),
    Question(question=" Which attribute uniquely identifies a user (e.g., uid, employeeNumber, entryUUID)?" , system_type="LDAP"),
    Question(question=" Can we perform a deep dive on a sample employee entry to review all relevant attributes and their values?" , system_type="LDAP"),
    Question(question=" Can we perform a deep dive on a sample external user entry to review all relevant attributes and their values?" , system_type="LDAP"),
    Question(question=" Which rules govern the provisioning of individual attributes (both standard and custom/extended attributes)?" , system_type="LDAP"),
    Question(question=" How is the user lifecycle managed at the attribute level (e.g., nsAccountLock, pwdAccountLockedTime, operational attributes for disabling)?" , system_type="LDAP"),
    Question(question=" What is the current process for account creation, modification, and disabling/deletion in the LDAP directory?" , system_type="LDAP"),
    Question(question=" Is account disabling handled via a specific attribute (e.g., nsAccountLock: true, pwdAccountLockedTime), entry removal, or relocation to a disabled subtree?" , system_type="LDAP"),
    Question(question=" How are user entries managed with respect to organizational attributes (e.g., o, ou, departmentNumber) for subtree placement or group membership?" , system_type="LDAP"),
    Question(question=" Which objectClass is used for groups (e.g., groupOfNames, groupOfUniqueNames, posixGroup, groupOfURLs for dynamic groups)?" , system_type="LDAP"),
    Question(question=" What is the approximate number of groups defined, and are meaningful descriptions (e.g., description attribute) available?" , system_type="LDAP"),
    Question(question=" How many managed applications are in scope, and is there an attribute available to identify the application associated with each group or entitlement?" , system_type="LDAP"),
    Question(question=" Are there standard groups that must be automatically assigned to specific user classes (e.g., by organization, country, role)?" , system_type="LDAP"),
    Question(question=" Which groups must be assigned by default based on specific rules (e.g., country, organization, role, contract type)?" , system_type="LDAP"),
    Question(question=" Are dynamic groups (e.g., memberURL-based) in use, and how should the IGA platform handle them?" , system_type="LDAP")
])

db.commit()
db.close()

print("Record iniziali inseriti.")